In [ ]:
# Лабораторная работа 1. Язык Python, основные библиотеки для анализа данных.

ФИО: Пиджакова Анна Геннадьевна

Группа: 317

In [1]:
import numpy as np
import pandas as pd

## Часть 1: Python

#### 1. Напишите код, который сформирует список всех натуральных чисел, не превосходящих 100, которые делятся на 7 и не делятся на 5. Нельзя использовать циклы — выполните это задание с помощью list comprehension.

In [2]:
a = [x for x in xrange(101) if x % 7 == 0 and x % 5 != 0]
a

[7, 14, 21, 28, 42, 49, 56, 63, 77, 84, 91, 98]

#### 2. Напишите функцию `sort_tokens(s)`, которая принимает на вход строку, разделяет ее на токены по запятым, сортирует токены с помощью функции `sorted()` и снова соединяет их в одну строку через запятые. Например, для строки `u"ночь,фонарь,улица"` функция должна выдать `u"ночь,улица,фонарь"`. Придумайте несколько входных строк и протестируйте функцию на них.

Обратите внимание, что склеить строки можно с помощью конструкции `'x'.join(...)`. Например:

In [2]:
'! '.join(['i', 'am', 'very', 'excited', ':-)'])

'i! am! very! excited! :-)'

In [8]:
sort_tokens = lambda s: ','.join(sorted(s.split(',')))
sort_tokens("11,333,666,222,777")

'11,222,333,666,777'

#### 3. Напишите функцию `remove_duplicates(a)`, которая принимает на вход список и возвращает его же, но без дубликатов и в отсортированном виде. Например, для списка `[u"ночь", u"улица", u"фонарь", u"аптека", u"аптека", u"улица", u"фонарь"]` результат должен быть `[u"аптека", u"ночь", u"улица", u"фонарь", ]`.

Подсказка: обратите внимание на структуру `set`!

In [5]:
remove_duplicates = lambda a: sorted(list(set(a)))

#### 4. Напишите функцию `word_counts(texts)`, которая принимает на вход список строк, и печатает пары (слово, число вхождений). Считайте, что слова в текстах могут быть разделены только пробелами. Например, для входа `[u'ночь улица фонарь аптека', u'аптека улица фонарь']` должно быть напечатано
>аптека 2

>улица 2

>фонарь 2

>ночь 1

Подсказки:

Чтобы разбить каждый из текстов на слова, воспользуйтесь функцией `map`, которая применяет заданную функцию к каждому элементу списка. Например, если бы нужно было каждый из текстов привести к нижнему регистру, то команда выглядела бы так:

In [3]:
map(lambda x: x.lower(), ["abCDefg", "HIjkL"])

['abcdefg', 'hijkl']

После первого шага вы получите список, состоящий из списков слов. Чтобы объединить их в один список слов, воспользуйтесь функцией `reduce`. Например, просуммировать числа из списка с ее помощью можно так:



In [4]:
reduce(lambda x, y: x + y, [1, 2, 3, 4, 5])

15

Для подсчета количества вхождений слов воспользуйтесь структурой `defaultdict` из модуля `collections`. В отличие от обычного `dict`, она не генерирует ошибку при обращении к несуществущему ключу, а создает новую запись, инициализируемую нулевым значением. Например:

In [9]:
from collections import defaultdict
d = defaultdict(int)
print (d)
d['abc'] += 1
print (d)
d['xxx']
print (d)

defaultdict(<class 'int'>, {})
defaultdict(<class 'int'>, {'abc': 1})
defaultdict(<class 'int'>, {'abc': 1, 'xxx': 0})


In [15]:
from collections import defaultdict
def word_count(texts):
    texts = list(reduce(lambda x,y: x+y , list(map(lambda x: x.split(' '), texts))))
    d = defaultdict(int)
    for x in texts:  d[x] += 1
    for x,y in d.items():  print(x,y)
word_count([u'11 222 vv rr ttt', u'11 2 vv ttt'] )

(u'11', 2)
(u'rr', 1)
(u'ttt', 2)
(u'2', 1)
(u'vv', 2)
(u'222', 1)


#### 5. (бонусное задание) Скачайте английский перевод "Преступления и наказания". Найдите 20 самых популярных слов и 20 слов, которые встречаются только один раз.

Приведите текст к нижнему регистру. Разделите текст на слова, считая разделителями все, кроме букв. Обратите внимание на функцию `split` из модуля `re`.

Не забудьте удалить пустые слова:
```
words = filter(lambda x: len(x) > 0, words)
```

In [11]:
from urllib import urlopen
url = "http://www.gutenberg.org/files/2554/2554.txt"
response = urlopen(url)
raw_text = response.read().decode('utf8')

In [12]:
raw_text[1000:1100]

u'r five\r\nchildren in only two rooms. The father and mother spent their evenings\r\nin reading aloud to '

In [13]:
import operator
import re

texts = re.sub(r'[^A-Za-z\']+|[_]', r' ',raw_text).split()
texts = list(map(lambda x: x.lower(),texts))
d = defaultdict(int)
for x in texts:
    d[x] += 1
d = (sorted(d.items(),key=operator.itemgetter(1))) #d <- list
print('20 наиболее часто встречающихся слов')
for i in range(1,21):
    print(d[-i][0])
print('20 слов, встречающихся по однуму разу')
i = 1
while i <= 20 and d[i][1] == 1:
    print(d[i][0])
    i += 1


20 наиболее часто встречающихся слов
the
and
to
he
a
i
of
you
in
it
that
was
his
at
her
but
not
with
for
she
20 слов, встречающихся по однуму разу
writings
nunnery
fedosya
clotted
preface
cyprus
increase
wheeled
superficially
meadows
fogeys
anaemic
straws
ivanitch's
busybody
reliable
her'
scraped
errors
cooking


## Часть 2: NumPy и SciPy

#### 1. Повторите 1000 раз следующий эксперимент: сгенерируйте две матрицы размера $10 \times 10$ из стандартного нормального распределения, перемножьте их (как матрицы) и найдите максимальный элемент. Какое среднее значение по экспериментам у максимальных элементов? 95-процентная квантиль?

Для вычисления квантили воспользуйтесь функцией `np.percentile`

In [61]:
?np.random.normal

In [81]:
mean_m = np.array([np.argmax(np.random.normal(0.0, 1.0, (10,10)).dot(np.random.normal(0.0, 1.0,(10,10)))) for i in xrange(1000)])
print np.mean(mean_m)
print np.percentile(mean_m, 95)

50.629
95.0


#### 2. Сгенерируйте 1000 чисел из распределения Пуассона с параметром $\lambda = 5$. Сформируйте массив, в котором в i-м элементе будет записано количество сгенерированных чисел, равных i.

Обратите внимание на функцию `np.bincount`

In [59]:
x = np.random.poisson(lam=5, size=(1000,))
w = np.bincount(x)
w

array([  4,  38,  84, 143, 175, 168, 156, 109,  55,  38,  23,   2,   4,   1])

#### 3. Реализуйте функцию, которая принимает на вход numpy-массив целых чисел `a`, и генерирует массив, в котором число `i` встречается `a[i]` раз. Протестируйте на результате из прошлого задания.

Обратите внимание на функцию `np.repeat`

In [60]:
def gen_array(y):
    x = np.arange(y.size)
    return np.repeat(x,y)
gen_array(w)   

array([ 0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3

#### 4. Напишите функцию `scale(X)`, которая принимает на вход матрицу и масштабирует каждый ее столбец (вычитает среднее и делит на стандартное отклонение). Убедитесь, что в функции не будет происходить деления на ноль. Протестируйте на каких-нибудь данных.

In [14]:
def scale(x):
    mean = np.mean(x, axis = 0)
    std = np.std(x, axis = 0)
    std[ std == 0] = 1
    x -= mean
    x /= std
    
x = np.array([[1,3,4,56,7],
              [2,4,5,6,7],
              [45,7,78,1,1]]).astype(np.float64)
scale(x)
x

array([[-0.73134485, -0.98058068, -0.72148745,  1.40942772,  0.70710678],
       [-0.68258853, -0.39223227, -0.69262795, -0.60404045,  0.70710678],
       [ 1.41393338,  1.37281295,  1.4141154 , -0.80538727, -1.41421356]])

#### 5. Сгенерируйте матрицу с элементами из нормального распределения $\mathcal{N}(10, 1)$. Найдите ее:
- определитель
- след
- наименьший и наибольший элементы
- спектральную норму
- норму Фробениуса
- собственные числа
- обратную матрицу

In [84]:
a = np.random.normal(size = (10,10),loc = 10, scale = 1)
det = np.linalg.det(a)
trace = np.trace(a)
maw_el = np.max(a)
min_el = np.min(a)
norm = np.linalg.norm(a, ord = 2)
fro_norm = np.linalg.norm(a, ord = 'fro')
eig, v = np.linalg.eig(a)
a_inv = np.linalg.inv(a)

## Часть 3: Pandas

#### Ответьте на вопросы о данных по авиарейсам в США за январь-апрель 2008 года.

Данные: http://stat-computing.org/dataexpo/2009/2008.csv.bz2
(обратите внимание, что распаковывать этот файл не обязательно — функция `pandas.read_csv` умеет читать из архивов автоматически)

Описание: http://stat-computing.org/dataexpo/2009/the-data.html

1. Какая из причин отмены рейса (`CancellationCode`) была самой частой? (расшифровки кодов можно найти в описании данных)
2. Найдите среднее, минимальное и максимальное расстояние, пройденное самолетом.
3. Не выглядит ли подозрительным минимальное пройденное расстояние? В какие дни и на каких рейсах оно было? Какое расстояние было пройдено этими же рейсами в другие дни?
4. Из какого аэропорта было произведено больше всего вылетов? В каком городе он находится?
5. Найдите для каждого аэропорта среднее время полета (`AirTime`) по всем вылетевшим из него рейсам. Какой аэропорт имеет наибольшее значение этого показателя?
6. Найдите аэропорт, у которого наибольшая доля задержанных (`DepDelay > 0`) рейсов. Исключите при этом из рассмотрения аэропорты, из которых было отправлено меньше 1000 рейсов (используйте функцию `filter` после `groupby`).

In [ ]:
from urllib.request import urlopen
url =  "http://stat-computing.org/dataexpo/2009/2008.csv.bz2"
response = urlopen(url)


In [6]:
df = pd.read_csv("2008.csv.bz2")

1.Какая из причин отмены рейса (CancellationCode) была самой частой? (расшифровки кодов можно найти в описании данных)
    Ответ: B(weather)

In [86]:
np.argmax(df.CancellationCode.value_counts())

'B'

2.Найдите среднее, минимальное и максимальное расстояние, пройденное самолетом.
    Ответ:  среднее расстояние - 726.387029
            минимальное - 11
            максимальное - 4962

In [87]:
df.Distance.describe()

count    7009728.000000
mean         726.387029
std          562.101803
min           11.000000
25%          325.000000
50%          581.000000
75%          954.000000
max         4962.000000
Name: Distance, dtype: float64

3.Не выглядит ли подозрительным минимальное пройденное расстояние? В какие дни и на каких рейсах оно было?    Какое расстояние было пройдено этими же рейсами в другие дни?
        Ответ:  да, выглядит
            15.05.2008 на рейсе 4988
            10.09.2008 на рейсе 5572
            рейс 4988:
                834    130
                96       1
                11       1
            рейс 5572:
                544    243
                11       1
    


In [98]:
df11 = df[df.Distance == 11]
print df11[['Year','Month','DayofMonth','DayOfWeek','FlightNum','UniqueCarrier']]

t4988 = df[df.FlightNum == 4988]
t5572 = df[df.FlightNum == 5572]

print t4988[df.UniqueCarrier == 'OH'].Distance.value_counts()

print t5572[df.UniqueCarrier == 'OH'].Distance.value_counts()

         Year  Month  DayofMonth  DayOfWeek  FlightNum UniqueCarrier
2547298  2008      5          15          4       4988            OH
4392215  2008      8          10          7       5572            OH
834    130
96       1
11       1
dtype: int64
544    243
11       1
dtype: int64


4.Из какого аэропорта было произведено больше всего вылетов? В каком городе он находится?
    Ответ: 'ATL', 6000 N Terminal Pkwy, Atlanta, GA 30320, Соединенные Штаты

In [99]:
np.argmax(df.Origin.value_counts())

'ATL'

5.Найдите для каждого аэропорта среднее время полета (AirTime) по всем вылетевшим из него рейсам. Какой аэропорт имеет наибольшее значение этого показателя?
    Ответ: 'SJU'

In [100]:
print(df.groupby('Origin').AirTime.mean())
np.argmax(df.groupby('Origin').AirTime.mean())

Origin
ABE     89.057518
ABI     36.789977
ABQ     91.657166
ABY     35.379759
ACK     50.692124
ACT     29.875977
ACV     58.850658
ACY    108.848214
ADK    151.423913
ADQ     41.987934
AEX     68.543556
AGS     36.933814
AKN     37.321429
ALB    101.860527
ALO     36.373134
AMA     56.196001
ANC    156.163749
ASE     48.307996
ATL     93.320419
ATW     50.696326
AUS    101.266600
AVL     69.899021
AVP     94.665204
AZO     34.846602
BDL    118.701612
BET     57.597815
BFL     64.024511
BGM     66.582260
BGR     90.211095
BHM     82.290713
          ...    
SPS     29.490040
SRQ    103.083807
STL     99.294409
STT    168.681929
STX    168.101176
SUN     48.221851
SUX     44.918919
SWF    132.768826
SYR     84.524087
TEX     93.124183
TLH     59.293080
TOL     48.295047
TPA    117.917963
TRI     47.871046
TUL     80.876802
TUP     42.900000
TUS     92.801864
TVC     49.328770
TWF     41.316563
TXK     43.796312
TYR     30.372715
TYS     81.030894
VLD     45.158351
VPS     75.231116
WRG

'SJU'

6.Найдите аэропорт, у которого наибольшая доля задержанных (DepDelay > 0) рейсов. Исключите при этом из рассмотрения аэропорты, из которых было отправлено меньше 1000 рейсов (используйте функцию filter после groupby).

In [7]:
grouped = df.groupby('Origin').filter(lambda x: len(x)>=1000)


In [9]:
filtred = grouped.groupby('Origin')
tmp = filtred.agg(lambda x: sum(x['DepDelay']>0)/float(len(x['DepDelay'])))['DepDelay']
max(tmp.iteritems(), key = lambda x: x[1])

('DAL', 0.57864189289422929)